plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.limbusshizuku'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.limbusshizuku'
        minSdk 26
        targetSdk 32
        versionCode 3
        versionName '1.0.2'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
